CREATE DATABASE customer_behavior;
use customer_behavior;
select * from customer limit 20;
-- Q1. Revenue generated by customers based on gender
SELECT 
    gender,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;


-- Q2. Customers who applied discounts and spent above average purchase amount
SELECT 
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount > (
        SELECT AVG(purchase_amount)
        FROM customer
    );


-- Q3. Top 5 products having highest average review ratings
SELECT 
    item_purchased AS product_name,
    ROUND(AVG(review_rating), 2) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;


-- Q4. Average purchase comparison between Standard and Express shipping
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS average_purchase
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Spending analysis of subscribed vs non-subscribed customers
SELECT 
    subscription_status,
    COUNT(customer_id) AS customer_count,
    ROUND(AVG(purchase_amount), 2) AS average_spending,
    ROUND(SUM(purchase_amount), 2) AS total_sales
FROM customer
GROUP BY subscription_status
ORDER BY total_sales DESC;


-- Q6. Top 5 products with highest discount usage percentage
SELECT 
    item_purchased,
    ROUND(
        (SUM(CASE 
                WHEN discount_applied = 'Yes' THEN 1 
                ELSE 0 
             END) * 100.0) / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;
-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
SELECT 
    customer_category,
    COUNT(*) AS total_customers
FROM
(
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases <= 1 THEN 'New Customer'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning Customer'
            ELSE 'Loyal Customer'
        END AS customer_category
    FROM customer
) AS customer_segments
GROUP BY customer_category;
-- Q8. Top 3 most purchased products in every category
SELECT 
    category,
    item_purchased,
    COUNT(*) AS total_orders
FROM customer
GROUP BY category, item_purchased
ORDER BY category, total_orders DESC;

-- Q9. Subscription pattern among repeat customers
SELECT 
    subscription_status,
    COUNT(*) AS repeat_customer_count
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. Revenue generated by different age groups
SELECT 
    age_group,
    ROUND(SUM(purchase_amount), 2) AS revenue_generated
FROM customer
GROUP BY age_group
ORDER BY revenue_generated DESC;
